"""Explicit native modeling examples; none are derived from the API manifest.

Each case exercises an actual constructor with non-default geometry parameters.
The service's serialized output is checked against an independently built shape.
"""

CASES = [
    ("box", "Box", [4, 6, 8], {}),
    ("box_rotation", "Box", [4, 6, 8], {"rotation": [15, 30, 45]}),
    ("cylinder", "Cylinder", [3, 7], {}),
    ("cylinder_sector", "Cylinder", [3, 7], {"arc_size": 210}),
    ("cone", "Cone", [4, 1, 7], {}),
    ("cone_sector", "Cone", [4, 1, 7], {"arc_size": 240}),
    ("sphere", "Sphere", [3], {}),
    ("sphere_partial", "Sphere", [3], {"arc_size1": -30, "arc_size2": 70, "arc_size3": 220}),
    ("torus", "Torus", [5, 1], {}),
    ("torus_sector", "Torus", [5, 1], {"major_angle": 220}),
    ("wedge", "Wedge", [4, 6, 8, 0, 0, 3, 5], {}),
    ("convex_polyhedron", "ConvexPolyhedron", [[[0, 0, 0], [3, 0, 0], [0, 4, 0], [0, 0, 5]]], {}),
    ("rectangle", "Rectangle", [7, 4], {}),
    ("rectangle_rotation", "Rectangle", [7, 4], {"rotation": 25}),
    ("rounded_rectangle", "RectangleRounded", [7, 4, 0.6], {}),
    ("circle", "Circle", [3], {}),
    ("circle_sector", "Circle", [3], {"arc_size": 230}),
    ("ellipse", "Ellipse", [4, 2], {"rotation": 25}),
    ("polygon", "Polygon", [[0, 0], [6, 0], [5, 3], [1, 4]], {}),
    ("regular_polygon", "RegularPolygon", [4, 7], {"rotation": 17}),
    ("trapezoid", "Trapezoid", [8, 3, 65], {"right_side_angle": 75}),
    ("triangle", "Triangle", [], {"a": 3, "b": 4, "c": 5}),
    ("slot_center_to_center", "SlotCenterToCenter", [6, 2], {"rotation": 12}),
    ("slot_center_point", "SlotCenterPoint", [[1, 2], [4, 2], 2], {}),
    ("slot_overall", "SlotOverall", [8, 3], {"rotation": 15}),
    ("superellipse", "Superellipse", [6, 4], {"order": 3, "point_count": 20}),
    ("line", "Line", [[0, 0, 0], [3, 4, 2]], {}),
    ("polyline", "Polyline", [[0, 0], [4, 0], [4, 3], [0, 2]], {}),
    ("polyline_closed", "Polyline", [[0, 0], [4, 0], [4, 3], [0, 2]], {"close": True}),
    ("fillet_polyline", "FilletPolyline", [[0, 0], [4, 0], [4, 4]], {"radius": 0.5}),
    ("spline", "Spline", [[0, 0], [2, 3], [4, 0], [6, 2]], {}),
    ("bezier", "Bezier", [[0, 0], [2, 4], [5, 3], [6, 0]], {}),
    ("bezier_weighted", "Bezier", [[0, 0], [2, 4], [5, 0]], {"weights": [1, 2, 1]}),
    ("bspline", "BSpline", [], {"control_points": [[0, 0], [2, 3], [4, 0]], "knots": [0, 0, 0, 1, 1, 1], "degree": 2}),
    ("center_arc", "CenterArc", [[1, 2], 3, 15, 240], {}),
    ("radius_arc", "RadiusArc", [[0, 0], [4, 0], 3], {}),
    ("three_point_arc", "ThreePointArc", [[0, 0], [2, 3], [4, 0]], {}),
    ("tangent_arc", "TangentArc", [[0, 0], [3, 2]], {"tangent": [1, 0]}),
    ("helix", "Helix", [2, 6, 3], {}),
    ("helix_conical", "Helix", [2, 6, 3], {"cone_angle": 10, "lefthand": True}),
    ("polar_line", "PolarLine", [[1, 2], 5], {"angle": 32}),
    ("jern_arc", "JernArc", [[0, 0], [1, 0], 3, 120], {}),
    ("sagitta_arc", "SagittaArc", [[0, 0], [4, 0], 1], {}),
    ("elliptical_center_arc", "EllipticalCenterArc", [[1, 2], 4, 2], {"start_angle": 25, "arc_size": 200, "rotation": 15}),
]
