import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import type { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import { createCadControls } from './controls'
import { createCadGroup, disposeCadGroup, frameCadCamera, type CadView } from '../../lib/three'
import type { RenderResult } from '../../lib/types'

type Stage = {
  renderer: THREE.WebGLRenderer
  scene: THREE.Scene
  camera: THREE.OrthographicCamera
  controls: OrbitControls
  group?: THREE.Group
  fit: () => void
  redraw: () => void
}

/** The hosted viewer consumes tessellations generated by the actual OCCT kernel. */
export function CadViewer({ model, modelId, title, view, edges, resetToken, screenshotToken }: {
  model: RenderResult | null
  modelId: string
  title: string
  view: CadView
  edges: boolean
  resetToken: number
  screenshotToken: number
}) {
  const host = useRef<HTMLDivElement>(null)
  const stage = useRef<Stage | null>(null)
  const current = useRef({ model, view, title })
  current.current = { model, view, title }
  const [error, setError] = useState<string>()

  useEffect(() => {
    const container = host.current!
    let renderer: THREE.WebGLRenderer
    try {
      renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true, preserveDrawingBuffer: true })
    } catch {
      setError('3D rendering is unavailable in this browser. Try a browser with WebGL enabled; source and geometry downloads remain available.')
      return
    }
    renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2))
    renderer.outputColorSpace = THREE.SRGBColorSpace
    renderer.setClearColor('#f5f7fb', 0)
    const canvas = renderer.domElement
    canvas.tabIndex = 0
    canvas.dataset.testid = 'sandbox-canvas'
    canvas.setAttribute('aria-label', `${current.current.title}: interactive 3D model. Drag to orbit, scroll to zoom, arrow keys to pan.`)
    container.appendChild(canvas)
    const scene = new THREE.Scene()
    scene.add(new THREE.HemisphereLight('#ffffff', '#c9d1dc', 2.5))
    const key = new THREE.DirectionalLight('#ffffff', 3)
    key.position.set(2, -3, 5)
    scene.add(key)
    const fill = new THREE.DirectionalLight('#d8e6ff', 1.2)
    fill.position.set(-3, 2, 1)
    scene.add(fill)
    const camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0.001, 1000)
    const initialTarget = frameCadCamera(camera, current.current.model?.bounds ?? null, current.current.view, container.clientWidth / Math.max(container.clientHeight, 1))
    let controls = createCadControls(camera, canvas, initialTarget)
    const redraw = () => renderer.render(scene, camera)
    const fit = () => {
      const width = Math.max(container.clientWidth, 1)
      const height = Math.max(container.clientHeight, 1)
      renderer.setSize(width, height)
      camera.zoom = 1
      controls.removeEventListener('change', redraw)
      controls.dispose()
      const target = frameCadCamera(camera, current.current.model?.bounds ?? null, current.current.view, width / height)
      controls = createCadControls(camera, canvas, target)
      controls.addEventListener('change', redraw)
      if (stage.current) stage.current.controls = controls
      redraw()
    }
    stage.current = { renderer, scene, camera, controls, fit, redraw }
    controls.addEventListener('change', redraw)
    const onKey = (event: KeyboardEvent) => {
      if (event.key !== '+' && event.key !== '=' && event.key !== '-') return
      event.preventDefault()
      camera.zoom = Math.max(0.15, Math.min(20, camera.zoom * (event.key === '-' ? 0.85 : 1.15)))
      camera.updateProjectionMatrix()
      redraw()
    }
    canvas.addEventListener('keydown', onKey)
    const observer = new ResizeObserver(() => {
      const width = Math.max(container.clientWidth, 1)
      const height = Math.max(container.clientHeight, 1)
      renderer.setSize(width, height)
      const halfHeight = (camera.top - camera.bottom) / 2
      camera.left = -halfHeight * width / height
      camera.right = halfHeight * width / height
      camera.updateProjectionMatrix()
      redraw()
    })
    observer.observe(container)
    fit()
    return () => {
      observer.disconnect()
      controls.removeEventListener('change', redraw)
      controls.dispose()
      canvas.removeEventListener('keydown', onKey)
      if (stage.current?.group) disposeCadGroup(stage.current.group)
      renderer.dispose()
      renderer.forceContextLoss()
      canvas.remove()
      stage.current = null
    }
  }, [])

  useEffect(() => {
    const state = stage.current
    if (!state) return
    if (state.group) { state.scene.remove(state.group); disposeCadGroup(state.group) }
    state.group = model ? createCadGroup(model, edges) : undefined
    if (state.group) state.scene.add(state.group)
    state.renderer.domElement.setAttribute('aria-label', `${title}: interactive 3D model. Drag to orbit, scroll to zoom, arrow keys to pan.`)
    state.redraw()
  }, [model, edges, title])

  useEffect(() => { stage.current?.fit() }, [model, view, resetToken])

  useEffect(() => {
    if (!screenshotToken || !stage.current) return
    const canvas = stage.current.renderer.domElement
    canvas.toBlob((blob) => {
      if (!blob) return
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `${current.current.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${current.current.view}.png`
      link.click()
      setTimeout(() => URL.revokeObjectURL(url), 1000)
    }, 'image/png')
  }, [screenshotToken])

  return <div className="cad-viewer relative h-full w-full [&>canvas]:block [&>canvas]:h-full [&>canvas]:w-full" ref={host} data-view={view} data-model-ready={Boolean(model)} data-model-id={model ? modelId : ''} data-mesh-count={model?.meshes.length ?? 0}>
    {error && <div className="absolute inset-0 flex items-center justify-center p-4 text-sm text-red-600" role="alert">{error}</div>}
  </div>
}
