import { beforeAll, describe, expect, test } from 'vitest'
import { BrowserKernel } from '../lib/kernel'
import { applyOperator, callMethod, getProperty, KernelLocation, KernelPlane, KernelVector, registerValues, setProperty } from '../lib/kernel/values'
import type { KernelContext } from '../lib/kernel/types'

let kernel: BrowserKernel
let ctx: KernelContext
beforeAll(async () => { kernel = await BrowserKernel.create(); ctx = kernel.context }, 120_000)
const call = (name: string, args: any[] = [], kwargs: Record<string, any> = {}) => ctx.invoke(name, args, kwargs)
const method = (target: any, name: string, args: any[] = [], kwargs: Record<string, any> = {}) => callMethod(target, name, args, kwargs, ctx)
const get = (target: any, name: string) => getProperty(target, name, ctx)

describe('local build123d value bindings', () => {
  test('vectors preserve coordinates and implement vector algebra', () => {
    const a = call('Vector', [1, 2, 3]), b = call('Vector', [[4, 5, 6]])
    expect(a.toTuple()).toEqual([1, 2, 3])
    expect(method(a, 'dot', [b])).toBe(32)
    expect(method(a, 'cross', [b]).toTuple()).toEqual([-3, 6, -3])
    expect(method(a, 'normalized').length).toBeCloseTo(1)
    expect(applyOperator('mul', [a, 2], ctx).toTuple()).toEqual([2, 4, 6])
    expect(method(new KernelVector(1, 0, 0), 'rotate', [call('Axis.Z'), 90]).Y).toBeCloseTo(1)
    expect(() => method(new KernelVector(), 'normalized')).toThrow(/zero-length/)
  })
  test('named planes preserve build123d handedness and coordinate transforms', () => {
    const plane = call('Plane.XZ') as KernelPlane
    expect(plane.y_dir.toTuple()).toEqual([0, 0, 1])
    expect(plane.z_dir.toTuple()).toEqual([0, -1, 0])
    expect(method(plane, 'from_local_coords', [[2, 3, 4]]).toTuple()).toEqual([2, -4, 3])
    expect(method(plane, 'to_local_coords', [[2, -4, 3]]).toTuple()).toEqual([2, 3, 4])
    expect(method(plane, 'offset', [2]).origin.toTuple()).toEqual([0, -2, 0])
  })
  test('location multiplication and inverse preserve transform order', () => {
    const translation = call('Pos', [1, 2, 3]), rotation = call('Rot', [0, 0, 90])
    const combined = applyOperator('mul', [translation, rotation], ctx) as KernelLocation
    expect(applyOperator('mul', [combined, [1, 0, 0]], ctx).toTuple()).toEqual([1, 3, 3])
    const identity = applyOperator('mul', [combined, method(combined, 'inverse')], ctx)
    expect(identity.position.length).toBeCloseTo(0)
    expect(identity.orientation.length).toBeCloseTo(0)
  })
  test('retains ShapeList handles for topology selections and slices', () => {
    const box = call('Box', [2, 3, 4]), edges = method(box, 'edges'), faces = method(box, 'faces')
    expect(edges.length).toBe(12)
    expect(faces.length).toBe(6)
    expect(edges.__cadValue).toBe('ShapeList')
    expect(kernel.encode(edges)).toMatchObject({ kind: 'ShapeList', $ref: expect.any(String) })
    const vertical = method(edges, 'filter_by', [call('Axis.Z')])
    expect(vertical.length).toBe(4)
    expect(vertical[0].owner).toBe(box)
    expect(method(edges, 'sort_by', [call('Axis.X')]).__cadValue).toBe('ShapeList')
    expect(method(faces, 'filter_by', [call('Axis.Z')]).length).toBe(2)
    expect(method(faces, 'filter_by', [call('Axis.Z')], { reverse: true }).length).toBe(4)
  })
  test('reports exact BRep properties and transformed native topology', () => {
    const box = call('Solid.make_box', [2, 3, 4]), translated = method(box, 'moved', [call('Pos', [10, 0, 0])])
    expect(get(box, 'volume')).toBeCloseTo(24)
    expect(get(box, 'area')).toBeCloseTo(52)
    expect(get(box, 'is_valid')).toBe(true)
    expect(method(box, 'bounding_box').min.X).toBeCloseTo(0)
    expect(method(translated, 'bounding_box').min.X).toBeCloseTo(10)
    expect(method(translated, 'bounding_box').max.X).toBeCloseTo(12)
    expect(method(box, 'vertices').length).toBe(8)
    expect(get(box, 'wrapped')).toBe(box)
  })
  test('curve factories provide precise circles, tangents and radii', () => {
    const circle = call('Edge.make_circle', [2]), line = call('Edge.make_line', [[0, 0, 0], [3, 4, 0]])
    expect(get(circle, 'length')).toBeCloseTo(4 * Math.PI)
    expect(get(circle, 'radius')).toBeCloseTo(2)
    expect(get(line, 'length')).toBeCloseTo(5)
    expect(method(line, 'start_point').toTuple()).toEqual([0, 0, 0])
    expect(method(line, 'end_point').toTuple()).toEqual([3, 4, 0])
  })
  test('native distance keys remain callable without a server', () => {
    const first = call('Solid.make_box', [1, 1, 1]), second = method(first, 'moved', [call('Pos', [3, 0, 0])])
    const key = call('topo_distance_to', [first])
    expect(key(second)).toBeCloseTo(2)
    expect(kernel.decode({ $apply: { target: kernel.encode(key), args: [kernel.encode(second)] } })).toBeCloseTo(2)
  })
  test('mutable location properties update BRep geometry and preserve absolute positioning', () => {
    const shape = call('Solid.make_box', [2, 3, 4])
    setProperty(shape, 'position', [10, 0, 0], ctx)
    expect(method(shape, 'bounding_box').min.X).toBeCloseTo(10)
    setProperty(shape, 'position', [20, 0, 0], ctx)
    expect(method(shape, 'bounding_box').min.X).toBeCloseTo(20)
    setProperty(shape, 'location', call('Pos', [0, 0, 0]), ctx)
    expect(method(shape, 'bounding_box').min.X).toBeCloseTo(0)
    setProperty(shape, 'orientation', [0, 0, 90], ctx)
    expect(method(shape, 'bounding_box').min.X).toBeCloseTo(-3)
    expect(get(shape, 'volume')).toBeCloseTo(24)
  })
  test('factories and face-wire methods keep retained inputs alive', () => {
    const face = call('Face.make_rect', [4, 6]), originalArea = get(face, 'area')
    const wire = method(face, 'outer_wire')
    expect(get(face, 'area')).toBeCloseTo(originalArea)
    expect(get(wire, 'length')).toBeCloseTo(20)
    expect(method(face, 'inner_wires')).toHaveLength(0)
    expect(get(face, 'area')).toBeCloseTo(originalArea)
    const shape = call('Solid.make_box', [2, 3, 4]), compound = call('Compound.make_compound', [[shape]])
    expect(get(shape, 'volume')).toBeCloseTo(24)
    expect(get(compound, 'volume')).toBeCloseTo(24)
  })
  test('solid static factories preserve native origins and optional angular sectors', () => {
    const cone = call('Solid.make_cone', [2, 1, 3]), cylinder = call('Solid.make_cylinder', [2, 3], { angle: 180 })
    expect(method(cone, 'bounding_box').min.X).toBeCloseTo(-2)
    expect(method(cone, 'bounding_box').min.Z).toBeCloseTo(0)
    expect(get(cone, 'volume')).toBeCloseTo(7 * Math.PI)
    expect(get(cylinder, 'volume')).toBeCloseTo(6 * Math.PI)
    expect(get(call('Solid.make_sphere', [2], { angle1: 0 }), 'volume')).toBeCloseTo(16 * Math.PI / 3)
  })
  test('oriented bounds and general matrix inverses use genuine geometry and algebra', () => {
    const box = method(call('Solid.make_box', [2, 3, 4]), 'rotate', [call('Axis.Z'), 32]), bounds = method(box, 'oriented_bounding_box')
    expect(bounds.size.toTuple().sort()).toEqual(expect.arrayContaining([expect.closeTo(2, 5), expect.closeTo(3, 5), expect.closeTo(4, 5)]))
    expect(method(bounds, 'is_outside', [[100, 100, 100]])).toBe(true)
    expect(method(bounds, 'is_outside', [bounds.center])).toBe(false)
    const matrix = call('Matrix', [[[2, 0, 0, 3], [0, 3, 0, 4], [0, 0, 4, 5]]]), inverse = method(matrix, 'inverse')
    const point = method(matrix, 'multiply', [[1, 2, 3]])
    expect(method(inverse, 'multiply', [point]).toTuple()).toEqual([expect.closeTo(1), expect.closeTo(2), expect.closeTo(3)])
  })
  test('grid and polar locations preserve centers, endpoint spacing and radial orientation', () => {
    const grid = call('GridLocations', [10, 20, 3, 2])
    expect(grid.locations.map((location: KernelLocation) => location.position.toTuple())).toEqual([[-10, -10, 0], [-10, 10, 0], [0, -10, 0], [0, 10, 0], [10, -10, 0], [10, 10, 0]])
    const polar = call('PolarLocations', [10, 3, 0, 180], { endpoint: true })
    expect(polar.locations[1].orientation.Z).toBeCloseTo(90)
    expect(polar.locations[2].position.X).toBeCloseTo(-10)
    const open = call('PolarLocations', [10, 3, 0, 180])
    expect(open.locations[2].orientation.Z).toBeCloseTo(120)
    const hex = call('HexLocations', [2, 2, 2])
    expect(hex.locations.map((location: KernelLocation) => location.position.Y)).toEqual([-3, 1, -1, 3])
    expect(hex.locations[0].position.X).toBeCloseTo(-Math.sqrt(3))
    expect(get(call('BuildPart'), 'part')).toBeNull()
  })
  test('delta and new_edges use native identity and boolean edge geometry', () => {
    const box = call('Box', [6, 6, 6]), cylinder = call('Cylinder', [1, 8]), cut = applyOperator('sub', [box, cylinder], ctx)
    expect(call('delta', [[box, cylinder], [box]])).toEqual([cylinder])
    expect(call('delta', [[box], [box, cylinder]])).toEqual([])
    const edges = call('new_edges', [box, cylinder], { combined: cut })
    expect(edges).toHaveLength(2)
    expect(edges.every((edge: any) => edge.owner === cut)).toBe(true)
    expect(edges.reduce((sum: number, edge: any) => sum + get(edge, 'length'), 0)).toBeCloseTo(4 * Math.PI)
    expect(get(box, 'volume')).toBeCloseTo(216)
  })
  test('transforms move assembly descendants without deleting their retained geometry', () => {
    const child = call('Solid.make_box', [2, 3, 4]), compound = call('Compound.make_compound', [[child]])
    const moved = method(compound, 'translate', [[10, 0, 0]])
    expect(method(moved.children[0], 'bounding_box').min.X).toBeCloseTo(10)
    const rotated = method(compound, 'rotate', [call('Axis.Z'), 90])
    expect(method(rotated.children[0], 'bounding_box').min.X).toBeCloseTo(-3)
    const scaled = method(compound, 'scale', [2])
    expect(get(scaled.children[0], 'volume')).toBeCloseTo(192)
    expect(get(child, 'volume')).toBeCloseTo(24)
  })
  test('projection workplanes and vector ShapeLists preserve native coordinates', () => {
    const plane = call('project_workplane', [[1, 2, 3], [1, 0, 1], [0, 0, 1], 5])
    expect(plane.origin.toTuple()).toEqual([1, 2, 8])
    expect(plane.x_dir.toTuple()).toEqual([1, 0, 0])
    const points = call('ShapeList', [[call('Vector', [3, 0, 0]), call('Vector', [1, 0, 0])]])
    expect(method(points, 'sort_by', [call('Axis.X')])[0].X).toBe(1)
    expect(() => call('project_workplane', [[0, 0, 0], [0, 0, 1], [0, 0, 1], 1])).toThrow(/zero-length/)
  })
  test('unimplemented operations fail explicitly and private methods are blocked', () => {
    expect(() => method(new KernelVector(), 'unsupported')).toThrow(/not implemented/)
    expect(() => method(new KernelVector(), '__proto__')).toThrow(/Private/)
    expect(() => get(new KernelVector(), '_hidden')).toThrow(/Private/)
    expect(registerValues(ctx)['Axis.X']([], {}, ctx).direction.toTuple()).toEqual([1, 0, 0])
  })
})
